CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'driver', 'student')),
    full_name VARCHAR(150),
    roll_number VARCHAR(50),
    department VARCHAR(120),
    contact_number VARCHAR(30),
    student_stop VARCHAR(150),
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    transport_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS routes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_name VARCHAR(100) NOT NULL UNIQUE,
    start_time TIME,
    end_time TIME,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS buses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_number VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'inactive' CHECK (status IN ('active', 'inactive', 'maintenance')),
    current_lat DECIMAL(10, 8),
    current_lng DECIMAL(11, 8),
    speed DECIMAL(6, 2) DEFAULT 0.00,
    route_id INTEGER REFERENCES routes(id) ON DELETE SET NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_buses_status ON buses (status);
CREATE INDEX IF NOT EXISTS idx_buses_route_id ON buses (route_id);

CREATE TABLE IF NOT EXISTS drivers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    contact VARCHAR(30),
    bus_id INTEGER UNIQUE REFERENCES buses(id) ON DELETE SET NULL,
    monthly_salary DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS driver_route_assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    route_id INTEGER NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    assignment_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_driver_assignment_day UNIQUE (driver_id, assignment_date)
);

CREATE INDEX IF NOT EXISTS idx_assignment_route_date ON driver_route_assignments (route_id, assignment_date);

CREATE TABLE IF NOT EXISTS bus_stops (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id INTEGER NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    stop_name VARCHAR(150) NOT NULL,
    lat DECIMAL(10, 8) NOT NULL,
    lng DECIMAL(11, 8) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bus_stops_route_id ON bus_stops (route_id);

CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts (created_at);

CREATE TABLE IF NOT EXISTS smart_stop_alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(100) NOT NULL,
    route_id INTEGER NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    stop_id INTEGER NOT NULL REFERENCES bus_stops(id) ON DELETE CASCADE,
    bus_id INTEGER REFERENCES buses(id) ON DELETE SET NULL,
    driver_id INTEGER REFERENCES drivers(id) ON DELETE SET NULL,
    student_lat DECIMAL(10, 8) NOT NULL,
    student_lng DECIMAL(11, 8) NOT NULL,
    distance_m DECIMAL(8, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'acknowledged', 'expired')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    acknowledged_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_smart_stop_alerts_route_status ON smart_stop_alerts (route_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_smart_stop_alerts_driver_status ON smart_stop_alerts (driver_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_smart_stop_alerts_bus_status ON smart_stop_alerts (bus_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_smart_stop_alerts_student_stop ON smart_stop_alerts (student_id, stop_id, status, expires_at);

CREATE TABLE IF NOT EXISTS usage_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(100) NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    lat DECIMAL(10, 8),
    lng DECIMAL(11, 8),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_usage_logs_student_time ON usage_logs (student_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_usage_logs_action_time ON usage_logs (action_type, timestamp);

CREATE TABLE IF NOT EXISTS student_favorites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    value VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_student_favorite UNIQUE (student_id, type, value)
);

CREATE INDEX IF NOT EXISTS idx_student_favorites_student_type ON student_favorites (student_id, type);

CREATE TABLE IF NOT EXISTS student_fee_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(100) NOT NULL,
    amount_paid DECIMAL(10, 2) NOT NULL,
    payment_date DATE NOT NULL,
    remarks VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_student_fee_payments_student_date ON student_fee_payments (student_id, payment_date);

CREATE TABLE IF NOT EXISTS staff_salary_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL REFERENCES drivers(id) ON DELETE CASCADE,
    salary_month DATE NOT NULL,
    amount_paid DECIMAL(10, 2) NOT NULL,
    paid_date DATE NOT NULL,
    remarks VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_staff_salary_payments_driver_month ON staff_salary_payments (driver_id, salary_month);

CREATE OR REPLACE FUNCTION set_buses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_buses_updated_at ON buses;
CREATE TRIGGER trg_buses_updated_at
BEFORE UPDATE ON buses
FOR EACH ROW
EXECUTE FUNCTION set_buses_updated_at();

INSERT INTO users (id, username, password, role, full_name, roll_number, department, contact_number, student_stop, is_blocked, transport_fee)
VALUES
    (1, 'admin', 'admin123', 'admin', NULL, NULL, NULL, NULL, NULL, FALSE, 0.00),
    (2, 'driver1', 'driver123', 'driver', NULL, NULL, NULL, NULL, NULL, FALSE, 0.00),
    (3, 'student1', 'student123', 'student', 'Student One', 'S1001', 'CSE', '9876500001', 'College Gate', FALSE, 12000.00)
ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    full_name = EXCLUDED.full_name,
    roll_number = EXCLUDED.roll_number,
    department = EXCLUDED.department,
    contact_number = EXCLUDED.contact_number,
    student_stop = EXCLUDED.student_stop,
    is_blocked = EXCLUDED.is_blocked,
    transport_fee = EXCLUDED.transport_fee;

INSERT INTO routes (id, route_name, start_time, end_time)
VALUES
    (1, 'Route A', '07:30:00', '09:00:00')
ON CONFLICT (id) DO UPDATE SET
    route_name = EXCLUDED.route_name,
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time;

INSERT INTO buses (id, bus_number, status, current_lat, current_lng, speed, route_id)
VALUES
    (1, 'BUS-101', 'active', 11.01680000, 76.95580000, 0.00, 1)
ON CONFLICT (id) DO UPDATE SET
    bus_number = EXCLUDED.bus_number,
    status = EXCLUDED.status,
    current_lat = EXCLUDED.current_lat,
    current_lng = EXCLUDED.current_lng,
    speed = EXCLUDED.speed,
    route_id = EXCLUDED.route_id;

INSERT INTO drivers (id, name, contact, bus_id, monthly_salary)
VALUES
    (1, 'driver1', '9876543210', 1, 18000.00)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    contact = EXCLUDED.contact,
    bus_id = EXCLUDED.bus_id,
    monthly_salary = EXCLUDED.monthly_salary;

INSERT INTO driver_route_assignments (driver_id, route_id, assignment_date)
VALUES
    (1, 1, CURRENT_DATE)
ON CONFLICT (driver_id, assignment_date) DO UPDATE SET
    route_id = EXCLUDED.route_id;

INSERT INTO bus_stops (route_id, stop_name, lat, lng)
SELECT 1, 'College Gate', 11.01720000, 76.95610000
WHERE NOT EXISTS (
    SELECT 1
    FROM bus_stops
    WHERE route_id = 1 AND stop_name = 'College Gate'
);

INSERT INTO alerts (message)
SELECT 'System initialized.'
WHERE NOT EXISTS (
    SELECT 1
    FROM alerts
    WHERE message = 'System initialized.'
);
